"""empty message

Revision ID: 453c63afd595
Revises: 
Create Date: 2018-05-08 20:24:06.481562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453c63afd595'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('exchange_symbol', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_symbol', name='_exch_symbol_uc')
    )
    op.create_table('industry_sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', name='_sector_title_uc')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=255), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('industry_sector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], ),
    sa.ForeignKeyConstraint(['industry_sector_id'], ['industry_sector.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_id', 'ticker_symbol', name='_stock_eid_symbol_uc')
    )
    op.create_table('stock_monthly_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('close_at', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'close_at', name='_smp_sid_price_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_monthly_price')
    op.drop_table('stock')
    op.drop_table('industry_sector')
    op.drop_table('exchange')
    # ### end Alembic commands ###
